
package swissindex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ws_Pharma_V101Soap", targetNamespace = "http://swissindex.e-mediat.net/SwissindexPharma_out_V101")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsPharmaV101Soap {


    /**
     * <p></p><p><b>Schema Output:</b> Click <a href='../schema/SwissindexPharma_out_V101.xsd'>here</a>
     * 
     * @param lang
     * @return
     *     returns swissindex.PHARMA
     */
    @WebMethod(operationName = "DownloadAll", action = "http://swissindex.e-mediat.net/SwissindexPharma_out_V101/DownloadAll")
    @WebResult(name = "PHARMA", targetNamespace = "http://swissindex.e-mediat.net/SwissindexPharma_out_V101", partName = "DownloadAllResult")
    public PHARMA downloadAll(
        @WebParam(name = "lang", targetNamespace = "http://swissindex.e-mediat.net/SwissindexPharma_out_V101", partName = "lang")
        String lang);

}
