
package webservice.erp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchGLNFoundException", targetNamespace = "http://service/")
public class NoSuchGLNFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchGLNFoundException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoSuchGLNFoundException_Exception(String message, NoSuchGLNFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoSuchGLNFoundException_Exception(String message, NoSuchGLNFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.erp.NoSuchGLNFoundException
     */
    public NoSuchGLNFoundException getFaultInfo() {
        return faultInfo;
    }

}
